spring.application.name=iic-management

spring.datasource.url=jdbc:mysql://localhost:3306/iic_management?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto = create

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.security.user.name=user
spring.security.user.password=password

spring.jpa.properties.hibernate.column_ordering_strategy=legacy